name: Greetings

on: [push]

jobs:
  buillding:
    runs-on: ubuntu-latest
    steps:
    - name: SSH DEPLOY
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/apps/siim-frontend
          git pull
          yarn
          yarn build
